services:
  backend:
    image: ghcr.io/kohlbacherlab/bwhc-backend:1.0-snapshot-broker-connector

    user: 0:0

    ports:
      - 9000:9000

    environment:
      ZPM_SITE: DnpmTest
      APPLICATION_SECRET: mydnpmsitedemosecret2023bywinner
      N_RANDOM_FILES: 50

    volumes:
      # External volume for config files with site-specific adaptations
      - /home/dnpm/bwhc_config:/bwhc_config

      # External volume for bwhc data persistence
      - /home/dnpm/bwhc_data:/bwhc_data

      

  frontend:
    image: ghcr.io/kohlbacherlab/bwhc-frontend:2209

    ports:
      - 3000:3000   # Adapt port mapping as needed

    environment:
      BACKEND_PROTOCOL: http        # Adapt protocol as needed
      BACKEND_HOSTNAME: localhost   # Adapt Backend hostname as needed
      BACKEND_PORT: 9000            # Adapt Backend port as needed
 #     NUXT_HOST: localhost              # Optionally override the host for the Nuxt server. Default: localhost
#      NUXT_PORT: 3000       # Optionally override the port on which the Nuxt server listens. Default: 3000

