### Example for docker-compose
version: '3.7'

volumes:
  data:

services:

  ### ETL-Processor
  etl-processor:
    ports:
      - 8080:8080
    image: ghcr.io/ccc-mf/etl-processor:latest
    network_mode: host
    environment:
      APP_REST_URI: https://dnpmtest.com/bwhc/etl/api
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost/etl
      SPRING_DATASOURCE_USERNAME: etl
      SPRING_DATASOURCE_PASSWORD: etl-password
      # For reverse proxy
      SERVER_FORWARD_HEADERS_STRATEGY: framework

  ### Database
  postgres:
    image: postgres:alpine
    network_mode: host
    environment:
      POSTGRES_DB: etl
      POSTGRES_USER: etl
      POSTGRES_PASSWORD: etl-password
    volumes:
      - data:/var/lib/postgresql/data
